test_variables = [
"test                    := n_photons"
]
pho_variables = [
      "npho                    := phoVector.size()",
      "pho1_pt                 := phoP4Corrected[0].pt()",
      "pho2_pt                 := phoP4Corrected[1].pt()",
      "pho3_pt                 := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].pt() : -1",
      "pho4_pt                 := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].pt() : -1",
      "pho1_eta                := phoP4Corrected[0].eta()",
      "pho2_eta                := phoP4Corrected[1].eta()",
      "pho3_eta                := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].eta() : -999",
      "pho4_eta                := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].eta() : -999",
      "pho1_phi                := phoP4Corrected[0].phi()",
      "pho2_phi                := phoP4Corrected[1].phi()",
      "pho3_phi                := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].phi() : -999",
      "pho4_phi                := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].phi() : -999",
      "pho1_energy             := phoP4Corrected[0].energy()",
      "pho2_energy             := phoP4Corrected[1].energy()",
      "pho3_energy             := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].energy() : -1",
      "pho4_energy             := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].energy() : -1",
      "pho1_old_r9             := phoP4Corrected[0].old_r9()",
      "pho2_old_r9             := phoP4Corrected[1].old_r9()",
      "pho3_old_r9             := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].old_r9() : -999",
      "pho4_old_r9             := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].old_r9() : -999",
      "pho1_full5x5_r9         := phoP4Corrected[0].full5x5_r9()",
      "pho2_full5x5_r9         := phoP4Corrected[1].full5x5_r9()",
      "pho3_full5x5_r9         := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].full5x5_r9() : -999",
      "pho4_full5x5_r9         := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].full5x5_r9() : -999",
      "pho1_EGMVA              := phoP4Corrected[0].userFloat('PhotonMVAEstimatorRun2Spring15NonTrig25nsV2p1Values')",
      "pho2_EGMVA              := phoP4Corrected[1].userFloat('PhotonMVAEstimatorRun2Spring15NonTrig25nsV2p1Values')",
      "pho3_EGMVA              := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].userFloat('PhotonMVAEstimatorRun2Spring15NonTrig25nsV2p1Values') : -999",
      "pho4_EGMVA              := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].userFloat('PhotonMVAEstimatorRun2Spring15NonTrig25nsV2p1Values') : -999",
      "pho1_MVA                := pho1_MVA",
      "pho2_MVA                := pho2_MVA",
      "pho3_MVA                := pho3_MVA",
      "pho4_MVA                := pho4_MVA",
      "pho1_match              := phoP4Corrected[0].genMatchType()",
      "pho2_match              := phoP4Corrected[1].genMatchType()",
      "pho3_match              := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].genMatchType() : -999",
      "pho4_match              := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].genMatchType() : -999",
      "pho1_pixelseed          := phoP4Corrected[0].hasPixelSeed()",
      "pho2_pixelseed          := phoP4Corrected[1].hasPixelSeed()",
      "pho3_pixelseed          := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].hasPixelSeed() : -999",
      "pho4_pixelseed          := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].hasPixelSeed() : -999",
      "pho1_electronveto       := phoP4Corrected[0].passElectronVeto()",
      "pho2_electronveto       := phoP4Corrected[1].passElectronVeto()",
      "pho3_electronveto       := ? phoP4Corrected.size() > 2 ? phoP4Corrected[2].passElectronVeto() : -999",
      "pho4_electronveto       := ? phoP4Corrected.size() > 3 ? phoP4Corrected[3].passElectronVeto() : -999",
      "pho12_dR                := deltaR( phoP4Corrected[0].eta, phoP4Corrected[0].phi, phoP4Corrected[1].eta, phoP4Corrected[1].phi )",
      "pho13_dR                := ? phoP4Corrected.size() > 2 ? deltaR( phoP4Corrected[0].eta, phoP4Corrected[0].phi, phoP4Corrected[2].eta, phoP4Corrected[2].phi ) : -1",
      "pho14_dR                := ? phoP4Corrected.size() > 3 ? deltaR( phoP4Corrected[0].eta, phoP4Corrected[0].phi, phoP4Corrected[3].eta, phoP4Corrected[3].phi ) : -1",
      "pho23_dR                := ? phoP4Corrected.size() > 2 ? deltaR( phoP4Corrected[1].eta, phoP4Corrected[1].phi, phoP4Corrected[2].eta, phoP4Corrected[2].phi ) : -1",
      "pho24_dR                := ? phoP4Corrected.size() > 3 ? deltaR( phoP4Corrected[1].eta, phoP4Corrected[1].phi, phoP4Corrected[3].eta, phoP4Corrected[3].phi ) : -1",
      "pho34_dR                := ? phoP4Corrected.size() > 3 ? deltaR( phoP4Corrected[2].eta, phoP4Corrected[2].phi, phoP4Corrected[3].eta, phoP4Corrected[3].phi ) : -1",
      "pho12_m                 := h4gPho12.mass",
      "pho13_m                 := h4gPho13.mass",
      "pho14_m                 := h4gPho14.mass",
      "pho23_m                 := h4gPho23.mass",
      "pho24_m                 := h4gPho24.mass",
      "pho34_m                 := h4gPho34.mass",
      "n_vertices              := Vertices.size()",
      "Vtx_x                   := Vertices[0].x()",
      "Vtx_y                   := Vertices[0].y()",
      "Vtx_z                   := Vertices[0].z()",
      "Vtx_hgg_x               := vertex_diphoton.x()",
      "Vtx_hgg_y               := vertex_diphoton.y()",
      "Vtx_hgg_z               := vertex_diphoton.z()",
      "genvertex_x             := genVertex.x()",
      "genvertex_y             := genVertex.y()",
      "genvertex_z             := genVertex.z()",
      "dZ_hggVtx               := genVertex.z() - vertex_diphoton.z()",
      "dZ_zeroVtx              := genVertex.z() - Vertices[0].z()",
      "dZ_randomVtx            := genVertex.z() - Vertex_random.z()",
      "BS_x                    := BSPoint.x()",
      "BS_y                    := BSPoint.y()",
      "BS_z                    := BSPoint.z()",
      "BS_factor_0Vtx          := BS_factor_0Vtx",
      "BS_factor_HggVtx        := BS_factor_HggVtx",
      "BS_factor_RandomVtx     := BS_factor_RandomVtx",
      "dZ_BS_zeroVtx           := BSPoint.z() - Vertices[0].z()",
      "dZ_BS_hggVtx            := BSPoint.z() - vertex_diphoton.z()",
      "n_diphotons             := diPhoPtrs.size()",
      "diPho0_logSumPt2        := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].logSumPt2() : -999",
      "diPho1_logSumPt2        := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].logSumPt2() : -999 ",
      "diPho2_logSumPt2        := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].logSumPt2() : -999 ",
      "diPho3_logSumPt2        := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].logSumPt2() : -999 ",
      "diPho4_logSumPt2        := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].logSumPt2() : -999 ",
      "diPho5_logSumPt2        := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].logSumPt2() : -999 ",
      "diPho0_ptBal            := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].ptBal() : -999",
      "diPho1_ptBal            := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].ptBal() : -999 ",
      "diPho2_ptBal            := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].ptBal() : -999 ",
      "diPho3_ptBal            := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].ptBal() : -999 ",
      "diPho4_ptBal            := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].ptBal() : -999 ",
      "diPho5_ptBal            := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].ptBal() : -999 ",
      "diPho0_ptAsym           := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].ptAsym() : -999",
      "diPho1_ptAsym           := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].ptAsym() : -999 ",
      "diPho2_ptAsym           := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].ptAsym() : -999 ",
      "diPho3_ptAsym           := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].ptAsym() : -999 ",
      "diPho4_ptAsym           := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].ptAsym() : -999 ",
      "diPho5_ptAsym           := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].ptAsym() : -999 ",
      "diPho0_NConv            := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].nConv() : -999",
      "diPho1_NConv            := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].nConv() : -999 ",
      "diPho2_NConv            := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].nConv() : -999 ",
      "diPho3_NConv            := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].nConv() : -999 ",
      "diPho4_NConv            := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].nConv() : -999 ",
      "diPho5_NConv            := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].nConv() : -999 ",
      "diPho0_PullConv         := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].pullConv() : -999",
      "diPho1_PullConv         := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].pullConv() : -999 ",
      "diPho2_PullConv         := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].pullConv() : -999 ",
      "diPho3_PullConv         := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].pullConv() : -999 ",
      "diPho4_PullConv         := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].pullConv() : -999 ",
      "diPho5_PullConv         := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].pullConv() : -999 ",
      "diPho0_SumPt            := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].sumPt() : -999",
      "diPho1_SumPt            := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].sumPt() : -999 ",
      "diPho2_SumPt            := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].sumPt() : -999 ",
      "diPho3_SumPt            := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].sumPt() : -999 ",
      "diPho4_SumPt            := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].sumPt() : -999 ",
      "diPho5_SumPt            := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].sumPt() : -999 ",
      "diPho0_PtLead           := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].leadingPhoton().pt() : -999",
      "diPho1_PtLead           := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].leadingPhoton().pt() : -999 ",
      "diPho2_PtLead           := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].leadingPhoton().pt() : -999 ",
      "diPho3_PtLead           := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].leadingPhoton().pt() : -999 ",
      "diPho4_PtLead           := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].leadingPhoton().pt() : -999 ",
      "diPho5_PtLead           := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].leadingPhoton().pt() : -999 ",
      "diPho0_PtSubLead        := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].subLeadingPhoton().pt() : -999",
      "diPho1_PtSubLead        := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].subLeadingPhoton().pt() : -999 ",
      "diPho2_PtSubLead        := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].subLeadingPhoton().pt() : -999 ",
      "diPho3_PtSubLead        := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].subLeadingPhoton().pt() : -999 ",
      "diPho4_PtSubLead        := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].subLeadingPhoton().pt() : -999 ",
      "diPho5_PtSubLead        := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].subLeadingPhoton().pt() : -999 ",
      "diPho0_Pt               := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].pt() : -999",
      "diPho1_Pt               := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].pt() : -999 ",
      "diPho2_Pt               := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].pt() : -999 ",
      "diPho3_Pt               := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].pt() : -999 ",
      "diPho4_Pt               := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].pt() : -999 ",
      "diPho5_Pt               := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].pt() : -999 ",
      "diPho0_mass             := ? diPhoPtrs.size() >= 1 ? diPhoPtrs[0].mass() : -999",
      "diPho1_mass             := ? diPhoPtrs.size() >= 2 ? diPhoPtrs[1].mass() : -999 ",
      "diPho2_mass             := ? diPhoPtrs.size() >= 3 ? diPhoPtrs[2].mass() : -999 ",
      "diPho3_mass             := ? diPhoPtrs.size() >= 4 ? diPhoPtrs[3].mass() : -999 ",
      "diPho4_mass             := ? diPhoPtrs.size() >= 5 ? diPhoPtrs[4].mass() : -999 ",
      "diPho5_mass             := ? diPhoPtrs.size() >= 6 ? diPhoPtrs[5].mass() : -999 ",

#      "dZ_sigmaZ               := BSPoint.sigmaZ()"
      # "dZ                      := genVertex.z() - vertex.z()",
      # "dZ_prime_check          := genVertex.z() - vtx_diphoton_z",
      # "Vtx_dipho_x             := vertex_diphoton.x()",
      # "Vtx_dipho_y             := vertex_diphoton.y()",
      # "Vtx_dipho_z             := vertex_diphoton.z()",







      # "gen_X                   := genVtx_x",
      # "gen_Y                   := genVtx_y",
      # "gen_Z                   := genVtx_z"
      # "n_vertices              := Vertices.size()",
      # "test                    := genVertex.z() - Vertices[0].z()"
    ]

dipho_variables = [
    "dp1_mass                := h4gDiPho1.mass() ",
    "dp2_mass                := h4gDiPho2.mass() ",
    "avg_dp_mass             := (h4gDiPho1.mass()+h4gDiPho2.mass())/2",
    "dp1_pt                  := h4gDiPho1.pt() ",
    "dp2_pt                  := h4gDiPho2.pt() ",
    "dp1_eta                 := h4gDiPho1.eta() ",
    "dp2_eta                 := h4gDiPho2.eta() ",
    "dp1_phi                 := h4gDiPho1.phi() ",
    "dp2_phi                 := h4gDiPho2.phi() ",
    "dp1_e                   := h4gDiPho1.energy() ",
    "dp2_e                   := h4gDiPho2.energy() ",
    "dp1_dr                  := deltaR(h4gDiPho1_Pho1.eta(), h4gDiPho1_Pho1.phi(), h4gDiPho1_Pho2.eta(), h4gDiPho1_Pho2.phi())",
    "dp2_dr                  := deltaR(h4gDiPho2_Pho1.eta(), h4gDiPho2_Pho1.phi(), h4gDiPho2_Pho2.eta(), h4gDiPho2_Pho2.phi())",
    "dp1_p1i                 := h4gDiPho1_iPho1",
    "dp1_p2i                 := h4gDiPho1_iPho2",
    "dp2_p1i                 := h4gDiPho2_iPho1",
    "dp2_p2i                 := h4gDiPho2_iPho2",
    "dp1_PtoverMass          := h4gDiPho1.mass()/h4gDiPho1.pt()",
    "dp2_PtoverMass          := h4gDiPho2.mass()/h4gDiPho2.pt()",
    "absCosThetaStar_CS      := abs(getCosThetaStar_CS(6500))",
    "absCosTheta_pho_a1      := abs(CosThetaAngles()[1])",
    "absCosTheta_pho_a2      := abs(CosThetaAngles()[0])"
]

tp_variables = [
    "tp_mass                 := h4gFourVect.mass()",
    "tp_pt                   := h4gFourVect.pt()",
    "tp_eta                  := h4gFourVect.eta()",
    "tp_phi                  := h4gFourVect.phi()",
    "tp_PtoverMass           := h4gFourVect.mass()/h4gFourVect.pt()"
]

ws_variables = [
   "tp_mass                 := h4gFourVect.mass()",
   "dp1_mass                := h4gDiPho1.mass() ",
   "dp2_mass                := h4gDiPho2.mass() ",
   "avg_dp_mass             := (h4gDiPho1.mass()+h4gDiPho2.mass())/2",
   "dZ                      := genVertex.z() - vertex.z()"
]
