import FWCore.ParameterSet.Config as cms

from flashgg.MicroAODProducers.flashggMicroAODSequence_cff import *
from flashgg.MicroAODProducers.flashggZeeDiPhotons_cfi import flashggZeeDiPhotons

flashggMicroAODZeeValidationSequence = cms.Sequence(flashggMicroAODSequence)
flashggMicroAODZeeValidationSequence.remove(flashggElectrons)
flashggMicroAODZeeValidationSequence.remove(flashggPreselectedDiPhotons)
flashggMicroAODZeeValidationSequence.remove(flashggJets)
flashggMicroAODZeeValidationSequence += flashggZeeDiPhotons
