#!/usr/bin/env bash
j=0
for((i=0;i<$1;i++));
do 
#  find ./Samples/Test_Cut_Signal_withTau/ -name *X$2*$i*.root
#  if [ $a ne 0 ]; then
file=./Samples/Test_Cut_Signal_test2_oldSample/output_ggF_X$2_WWgg_lnulnugg_$i.root
#echo "$file"
if [ ! -f "$file" ]; then
  j = $j + 1
  echo -e "$i \c"
  fi
done
echo "j= $j"

