+JobFlavour   = "longlunch"

+OnExitHold   = ExitStatus != 0 

periodic_release =  (NumJobStarts < 4) && ((CurrentTime - EnteredCurrentStatus) > 60) 

input         = /afs/cern.ch/user/c/chuw/.dasmaps/das_maps_dbs_prod.js 
executable    = HHWWgg_v2-6_Trees_X600_Test/runJobs0.sh
arguments     = $(ProcId)
output        = HHWWgg_v2-6_Trees_X600_Test/runJobs0_$(ClusterId).$(ProcId).out
error         = HHWWgg_v2-6_Trees_X600_Test/runJobs0_$(ClusterId).$(ProcId).err
log           = HHWWgg_v2-6_Trees_X600_Test/runJobs0_$(ClusterId).$(ProcId)_htc.log

max_retries   = 1
queue 192 
